### ISSUE TITLE
Build Error: sawUniversalRobot Not Found

### ISSUE THREAD

**Issue by liushuya7** [jhu-saw/sawUniversalRobotROS2#1]
Hi Anton,

It seems like all other packages were built successfully except this one which complained about **sawUniversalRobot** not being found.

```bash
Starting >>> universal_robot
--- stderr: universal_robot                               
CMake Error at CMakeLists.txt:49 (find_package):
  By not providing "FindsawUniversalRobot.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "sawUniversalRobot", but CMake did not find one.

  Could not find a package configuration file provided by "sawUniversalRobot"
  (requested version 1.1.0) with any of the following names:

    sawUniversalRobotConfig.cmake
    sawuniversalrobot-config.cmake

  Add the installation prefix of "sawUniversalRobot" to CMAKE_PREFIX_PATH or
  set "sawUniversalRobot_DIR" to a directory containing one of the above
  files.  If "sawUniversalRobot" provides a separate development package or
  SDK, be sure it has been installed.

---
Failed   <<< universal_robot
```
Under `/install/sawUniversalRobot/share/sawUniversalRobot/`, I did not find `sawUniversalRobotConfig.cmake`.

I appreciate your help.

**Comment by adeguet1** [comment]
This is untested on real robot so proceed with caution.   You need to make sure you use the feature-updated-CMake-ros branch for the repository sawUniversalRobot.

---

On Jun 8, 2023, at 3:29 PM, Joshua Liu ***@***.***> wrote:

﻿

Hi Anton,

It seems like all other packages were built successfully except this one which complained about sawUniversalRobot not being found.

Starting >>> universal_robot
--- stderr: universal_robot
CMake Error at CMakeLists.txt:49 (find_package):
  By not providing "FindsawUniversalRobot.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "sawUniversalRobot", but CMake did not find one.

  Could not find a package configuration file provided by "sawUniversalRobot"
  (requested version 1.1.0) with any of the following names:

    sawUniversalRobotConfig.cmake
    sawuniversalrobot-config.cmake

  Add the installation prefix of "sawUniversalRobot" to CMAKE_PREFIX_PATH or
  set "sawUniversalRobot_DIR" to a directory containing one of the above
  files.  If "sawUniversalRobot" provides a separate development package or
  SDK, be sure it has been installed.

---
Failed   <<< universal_robot

Under /install/sawUniversalRobot/share/sawUniversalRobot/, I did not find sawUniversalRobotConfig.cmake.

I appreciate your help.

**Comment by liushuya7** [comment]
Thanks, @adeguet1! I tested it on a CB2 UR5 robot. It seems working fine with a nice GUI.
![Screenshot_20230614_141756](https://github.com/jhu-saw/sawUniversalRobotROS2/assets/6867028/b323de7b-3f00-4e37-be9b-74d35598940a)
