### ISSUE TITLE
mtsUniversalRobotScriptRT: UR:control: robot not ready

### ISSUE THREAD

**Issue by liushuya7** [jhu-saw/sawUniversalRobotROS2#3]
Hi @adeguet1 ,

The driver is up running fine.
```bash
$ ros2 run universal_robot universal_robot -i 10.162.34.13
Options provided:
 - IP address for the UR controller [10.162.34.13]

File: mtsUniversalRobotScriptRT.cpp Line: 310 -  need to add joint configuration with names, type and maybe limits?  Can we retrieve these via API?
-W Class mtsUniversalRobotScriptRT: ReadPolyscopeVersion: version = 1.8.16941
[INFO] [1687817859.386599241] [rclcpp]: 1687817859.285494s, #1: UR: socket connected, IP: 10.162.34.13
[INFO] [1687817859.386721652] [rclcpp]: 1687817859.285741s, #2: UR-DashboardServer: Connected: Universal Robots Dashboard Server
```

I wrote two nodes to publish `geometry_msgs::PoseStamped` msg to `/move_cp` and to publish `sensor_msgs::JointState` msg to `/move_jp`. But the robot doesn't move and it gave a warning once the driver receives the msg:

```bash
-W Class mtsUniversalRobotScriptRT: UR:control: 1.68782e+09s, #1: UR: robot not ready
[WARN] [1687817875.806164874] [rclcpp]: 1687817875.805913s, #1: UR: robot not ready
-W Class mtsUniversalRobotScriptRT: UR:control: 1.68782e+09s, #2: UR: robot not ready
[WARN] [1687817885.806314887] [rclcpp]: 1687817885.806022s, #2: UR: robot not ready
-W Class mtsUniversalRobotScriptRT: UR:control: 1.68782e+09s, #3: UR: robot not ready
[WARN] [1687817895.814549742] [rclcpp]: 1687817895.814160s, #3: UR: robot not ready

```

Is there anything else I missed?

**Comment by adeguet1** [comment]
Which generation are you using?  I'm not totally sure but I believe you need to enable the programming interface on the pendant on the latest URs.  Maybe @pkazanzides can comment on this.

Correction: there's a note on the main repo README: https://github.com/jhu-saw/sawUniversalRobot/blob/devel/README.md

**Comment by liushuya7** [comment]
I am using a CB2 Universal Robot with Polyscope 1.8

**Comment by pkazanzides** [comment]
For move_jp and move_cp, the "Robot Not Ready" message (actually an event) indicates that either the power is off or the robot is not in the IDLE state (e.g., it is already moving).

**Comment by liushuya7** [comment]
I just tested the same code on UR e-series robots and it works fine. I guess this UR driver doesn't work with CB2 robots anymore？

**Comment by pkazanzides** [comment]
It should still work with CB2.  But, since my CB2 controller broke, I have not been able to test it.

**Comment by liushuya7** [comment]
I tested it on a real CB2 robot and the driver works. Earlier I was working with CB2 UR-Sim, it doesn't work with UR-Sim. Thanks!
